type:
  automation:
    resource: workflow
  config:
  name: ${{ values.projectName }}-${{ values.teamIdentifier }}-${{ values.releaseStage}} Validation
  template: workflow.json
  parameters:
    owner: ${{ values.teamIdentifier }}
    proj_name: ${{ values.projectName }}
    stage: ${{ values.releaseStage }}
    guardian_id:
      type: reference
      project: srg
      configType: app:dynatrace.site.reliability.guardian:guardians
      configId: ${{ values.projectName }}-${{ values.teamIdentifier }}-${{ values.releaseStage}}_validation
      property: id
  skip: false
