apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  labels:
    dt.owner: "platform_team"
    app_name: "kubeaudit"
    proj_name: "platform"
    stage: "production"
    owner: "platform_team"    
    version: "1.0"    
  name: kubeaudit
  namespace: argocd
spec:
  sources:
    - repoURL: 'FORKED_TEMPLATE_REPO_PLACEHOLDER.git'
      targetRevision: main
      path: "manifests/platform/kubeaudit"
  destination:
    namespace: kubeaudit
    server: 'https://kubernetes.default.svc'
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2