---
monacoVersion: "2.14.2"
gitlab_group: "group1"
argocd_gitlab_generator_owner: "group2"
gitlab_backstage_template_repo_name: "backstage-templates"
gitlab_app_template_repo_name: "applications-templates"
gitlab_platform_repo_name: "platform"
dynatrace_geolocation: "GEOLOCATION-DDAA176627F5667A"